### ISSUE TITLE
configurable ca path

### ISSUE THREAD

**Issue by sanyatuning** [confirm/PhpZabbixApi#25]
pls create an optin to set ssl capath option
see http://php.net/manual/en/context.ssl.php

somethinng like this
```
        // do request
        $streamContext = stream_context_create(array(
            'http' => array(
                'method'  => 'POST',
                'header'  => 'Content-type: application/json-rpc'."\r\n".$this->extraHeaders,
                'content' => $this->requestEncoded
            ),
            'ssl' => array(
                'verify_peer'       => $this->verifyPeer,
                'verify_peer_name'  => $this->verifyPeer,
                'capath'            => $this->caPath,
            )
        ));

```

**Comment by domibarton** [comment]
You can now easily overwrite the [SSL context](http://php.net/manual/en/context.ssl.php) in the [constructor](https://github.com/confirm/PhpZabbixApi/blob/master/templates/abstract.tpl.php#L148) or via [setSslContext() method](https://github.com/confirm/PhpZabbixApi/blob/master/templates/abstract.tpl.php#L233), which means:

```
```

**Comment by domibarton** [comment]
@sanyatuning feel free to use [v2.2.4](https://github.com/confirm/PhpZabbixApi/releases/tag/v2.2.4) or [v2.4.4](https://github.com/confirm/PhpZabbixApi/releases/tag/v2.4.4)
