### ISSUE TITLE
Attempted to call function  \"posix_getuid\" - Not supported on Windows PHP

### ISSUE THREAD

**Issue by Newan** [confirm/PhpZabbixApi#29]
This function \"posix_getuid\"  is not defined on Windows PHP:
ZabbixApiAbstract.class.php","line":498

**Comment by irongomme** [comment]
Can you send more details of your environment ? (php version, php extensions loaded, etc ... )

**Comment by Newan** [comment]
Installed over Xammp (https://www.apachefriends.org/index.html) on Windows 10:

PS H:\> php --version
PHP 5.5.15 (cli) (built: Jul 23 2014 15:05:09)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
PS H:\>

[php.ini.txt](https://github.com/confirm/PhpZabbixApi/files/436684/php.ini.txt)

**Comment by irongomme** [comment]
Effectively, the posix_getuid will not works on Windows : 

PHP Doc : Note: This extension is not available on Windows platforms.

But, this method is just responsible for a unique cache key, you could use session_id() instead if you use sessions in your php app ... 

Let us know if it works 

But my personnal advice is to prefer Linux like system for dev. And if you can't, take a look on Docker or Bash for windows to install php over a linux base.

**Comment by domibarton** [comment]
We can try to fix it by implementing a workaround for windows (e.g. reverting 48e528cc997ad90a2ffe16770355866ba002b34b but only for Windows).

**Comment by irongomme** [comment]
Yes but it introduce risk to have a duplicate cache key if the same user is logged twice or more ... isn't it ?

**Comment by domibarton** [comment]
We already have that right now on POSIX-compatible systems, because we might need it when there are two different OS users trying to connect with the same Zabbix user. Of course we could use the same token key for both OS users (same Zabbix user & permissions in the end), but there might be a OS permission conflict and for that case we're adding the OS UID to the filename, so that both OS users can read-write their token files. 

In case for windows we lose this feature, but there's no "easy" alternative solution for Windows.

**Comment by Newan** [comment]
O.k i can test it tomorrow  It is possible to deaktivate the Session Cache, because is it the dev Maschine

**Comment by domibarton** [comment]
I suppose you're german speaking, so…

Was willst du genau machen, bzw. welchen Session Cache moechtest du deaktiveren? Dass der Token nicht mehr zwischengespeichert wird? Falls du das unterbinden moechtest, kannst du einfach das $tokenCacheDir Argument (4. Argument) beim `userLogin()` weglassen:

Hier ein Beispiel:

```
$api = new ZabbixApi('http://zabbix.confirm.ch/api_jsonrpc.php');
api->userLogin(array('user' => 'dein_user', 'password' => 'dein_passwort', '', false));
```

**Comment by Newan** [comment]
Ja mein Englisch ist wahrlich nicht das beste XD.

Super damit komm ich doch klar, dann kann ich auf meinen Entwicklungsrechner den CacheDir weglassen (unter Windows) und auf den Servern läuft ja eh Linux. Damit ist das für mcih erledigt. Danke
