### ISSUE TITLE
triggerGet - Not returning triggers where group id > 11

### ISSUE THREAD

**Issue by geftactics** [confirm/PhpZabbixApi#30]
Odd one... Could be me doing something wrong...

Zabbix 2.4.8
phpZabbixApi - Downloaded release v2.4.5.tar.gz and copied 2x files from build into my lib dir.

I've got a PHP page that shows us any active triggers, we notice that the API isn't retrieving certain ones.

After some debugging, I found that it's related to the hostgroup of the host that the trigger is for. Certain hostgroups don't have their alerts shown.

I inspected the database, to try and spot differences between hostgroups that worked, and ones that didn't - All that I could determine was that any hostgroups with id > 11 are affected.

If I move my host into a hostgroup with id < 11, then triggers start appearing!!!

I've also tried specifically settings groupid on triggerGet, but specifying a hostgroup > 11 doesn't grab any results.

I've attached a test php file - It may help with debugging!

**Comment by squiggleuk** [comment]
[triggers.php.txt](https://github.com/confirm/PhpZabbixApi/files/268232/triggers.php.txt)

**Comment by domibarton** [comment]
Sorry for my late reply @squiggleuk, but is this probably related to #36 ?
