### ISSUE TITLE
API error -32602: Not authorised

### ISSUE THREAD

**Issue by boyemillar** [confirm/PhpZabbixApi#32]
Hi... I'm using LDAP Authentication on Zabbix v3.0.3 and cant seem to get the PHP API to work.

I Just get the following error... or sometimes a completely blank page

API error -32602: Not authorised

**Comment by domibarton** [comment]
I don't know, but this seems to be an API error not a PhpZabbixApi. Have you checked the permissions of the user in the Zabbix WebUI? Is API access allowed?
