### ISSUE TITLE
HostCreate impossible if groupid >= 10

### ISSUE THREAD

**Issue by toine7m** [confirm/PhpZabbixApi#36]
Hostgroup cannot be over 10 or it returns an error 

API error -32500: No permissions to referred object or it does not exist!

**Comment by domibarton** [comment]
I think this is a Zabbix API error and not one of my library…
I'll only return what the Zabbix API is returning.

Are you sure your host group exists and you've access to it?

**Comment by toine7m** [comment]
Yep it's a Zabbix API problem, you've to put everything in an array if you don't want any problem with hostgroup >10...

**Comment by toine7m** [comment]
You have to put your data between [mydata] to avoid this issue.

Le ven. 27 juil. 2018 à 18:25, MIchaelOldman77 <notifications@github.com> a
écrit :
