### ISSUE TITLE
release to Zabbix 3.0

### ISSUE THREAD

**Issue by joseamarildo** [confirm/PhpZabbixApi#37]
Hi, 

I'm sorry if I'm not in the right place to make this question but I would like to know if you have any plan to relaease it to Zabbix 3.0. 

Thank you for the great work you did.

**Comment by domibarton** [comment]
Hi there,

Didn't had a look at the 3.0 API so far, as I'm no longer developing w/ PHP.
If the 3.0 API is alike w/ the 2.4 version, then it shouldn't be a huge "thing" to do…

@Karsonito do you still use the API and did you probably have a look at 3.0?

**Comment by domibarton** [comment]
I gave it a try and…

- downloaded the latest 3.2 sources
- pointed the `PATH_ZABBIX` of the `config.inc.php` to the 3.2 `frontend/php/` directory
- ran `php build.php`

The library was built and there wasn't an error. There are some major differences when I've ran a `git diff`. However, I didn't check them properly.

@joseamarildo As mentiond in #28 , I'm looking for contributors. If you want to help, can you try to build the library by yourself and test it against a Zabbix 3.2 installation?

**Comment by Karsonito** [comment]
@domibarton Yes, still using 2.4. May be one day we will try new verson

**Comment by joseamarildo** [comment]
Hi, I tested the pre-built files to authenticate in the version 3.0.9 and it worked without errors. I'm sorry I didn't have the opportunity to test in 3.2 so far.

**Comment by domibarton** [comment]
@joseamarildo thanks mate - awesome! :) 

I've a 3.2 installation here, I'll make a few tests when I find the time. I'll also have a look at Zabbix' codebase. When it works out, I think we can release the API as beta for 3.x…

**Comment by execthis** [comment]
Hi, we upgraded Zabbix 2.2 to 3.2 a few days ago. After rebuilding the API with 3.2 source files and a few changes in the requests I can confirm that its working very well for 3.2.

**Comment by alphaonex86** [comment]
Hi, I'm newbies, I don't understand how work with the version 3.2+

**Comment by phansys** [comment]
@joseamarildo, currently, this library should work with Zabbix 3.0. Even, the latest tested version is 4.4.
Take a look at the build results: https://travis-ci.org/confirm/PhpZabbixApi.
We'll publish a new release soon.
Please, feel free to reopen if something is not working as expected.
Thank you!
