### ISSUE TITLE
Failed step of scenario example

### ISSUE THREAD

**Issue by alphaonex86** [confirm/PhpZabbixApi#43]
Hi,

I don't found a way to get "Failed step of scenario", I wish get the web scenario failed more than retry count to see if I have any failed pending. I add search too by httptestid, but failed.

Cheers,

**Comment by ojgarciab** [comment]
Could you describe us a [reproducible scenario](https://stackoverflow.com/help/minimal-reproducible-example), expected and current behavior?

**Comment by alphaonex86** [comment]
I search sample code to get  "Failed step of scenario" of web checks.
expected: found sample code
current behavior: not found sample code

**Comment by ojgarciab** [comment]
How are you looking for that? Could you share your code?
**There is no examples of that**: https://github.com/confirm/PhpZabbixApi/blob/master/README.md
Where did you found the sample code? Are you asking for an example?

**Comment by ojgarciab** [comment]
Quick sample code:

```
$webcheckData = $api->webcheckGet([
  'output' => 'extend',
  'search' => [
    'name' => 'Test scenario',
  ],
  'selectHosts' => 'extend',
]);
foreach ($webcheckData as $data) {
  echo 'Host: ', $data->hosts[0]->host, ', status: ', $data->status, PHP_EOL;
}
```

**Comment by ojgarciab** [comment]
Quick sample code:

```
$itemData = $api->itemGet([
  'host' => '...',
  'search' => [
    'key_' => 'web.test.fail',
  ],
  'webitems' => true,
]);
foreach($itemData as $data) {
  echo 'Host: ', $data->host, ', key: ', $data->key_, ', last value: ', $data->lastvalue, PHP_EOL;
}
```

It is important to set `webitems` flag.
