### ISSUE TITLE
Problem with RHEL8 PHP 7.2 Zabbix 5.0.5

### ISSUE THREAD

**Issue by eschi1** [confirm/PhpZabbixApi#58]
I have an issue with my custom script and your api file. When I run my script I get "could not connect to https://localhost/zabbix/api_jsonrpc.php". 
The same script is working on RHEL7 PHP 7.2. I can also connect to the API from RHEL7 Server to RHEL8 Server. So there is no permission / firewall issue.
When I use your latest file from 2020 I get no error message at all.

**Comment by phansys** [comment]
Sorry for the delay @eschi1.
Are you still experiencing the issue? If yes, could you please try using the `3.x` version?
Even if this version is not implementing all the available methods from Zabbix 5.x, this will be a good option to debug the problem.
```
composer require confirm-it-solutions/php-zabbix-api:^3.0@dev
```
I'll be waiting for your feedback.
Thank you.

**Comment by eschi1** [comment]
Hi,
I was able to track it down to some SSL problem befor your respond. And yes its working with the dev version. 

Thanks

**Comment by phansys** [comment]
Good news!
Thank you for your patience and feedback.
